-- --------------------------------------------------------
-- Robotinfo DATABASE
-- (c) 2021 Dennis Giese (dennis [at] dontvacuum.me)
-- This DB generates https://dontvacuum.me/robotinfo/
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `robotinfo`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `robotinfo` (
  `id` int NOT NULL AUTO_INCREMENT,
  `modelname` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `OEM` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `SKU` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `region` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `codename` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `firmwareformat` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `firmwareformat-more` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `voiceformat` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `voiceformat-more` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `SOC` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'Allwinner R16 (4x)',
  `RAM` int DEFAULT '512',
  `RAM-text` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '512 MByte',
  `Flash` int DEFAULT '256',
  `Flash-text` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '256MByte NAND',
  `MCU` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `WiFi` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `variant` int NOT NULL DEFAULT '0',
  `OS` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `Kernel` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `ReleasedQ` int DEFAULT NULL,
  `ReleasedY` int DEFAULT NULL,
  `firmwareformat-link` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `voiceformat-link` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_LIDAR` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_Camera` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_Mop` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_Waterpump` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_Basestation` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_Towerbumper` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_IR_dropsensors` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_IR_sidesensors` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_frontsensor` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `feat_carpetsensor` varchar(100) DEFAULT NULL,
  `feat_rolltype` varchar(100) DEFAULT NULL,
  `cloud_miio_version` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `cloud_other` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `support_root` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `support_root_since` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `support_root_public` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `support_valetudo` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `res_teardown` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `support_root_complexity` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `res_config_files` varchar(200) DEFAULT NULL,
  `res_builder` varchar(200) DEFAULT NULL,
  `res_picture` varchar(200) DEFAULT NULL,
  `res_root_howto` varchar(200) DEFAULT NULL,
  `comments` text,
  `status` varchar(300) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `warning` varchar(10) DEFAULT NULL,
  `EOL` int DEFAULT NULL,
  `Active` int DEFAULT NULL,
  `amazon_coupons` varchar(150) DEFAULT NULL,
  `amazon_com_affil` varchar(400) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `amazon_de_affil` varchar(400) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `amazon_fr_affil` varchar(400) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `amazon_it_affil` varchar(400) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `amazon_uk_affil` varchar(400) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `asin_us` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `asin_eu` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `asin_uk` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `tuev_certified` varchar(150) DEFAULT NULL,
  `fccid` varchar(150) DEFAULT NULL,
  `fccid_url` varchar(300) DEFAULT NULL,
  `basestation` varchar(150) DEFAULT NULL,
  `autoempty` int DEFAULT '0',
  `autowash` int DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=79 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `robotinfo` WRITE;
/*!40000 ALTER TABLE `robotinfo` DISABLE KEYS */;
INSERT INTO `robotinfo` VALUES (1,'dreame.vacuum.mc1808','Xiaomi Vacuum 1C','Dreame','STYTJ01ZHM',NULL,'p1904','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',4,2019,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2008/voices/soundpackage.json','n','y (1x OV7251 up facing[640x480])','y','y','n','n','4x + 1x',NULL,'IR bar','y (IR)','rubber+brush','3.5.8',NULL,'y','Q4/2019','y','y','https://dontvacuum.me/teardowns/xiaomi-1c/','easy via UART, minimal teardown','https://dontvacuum.me/robotinfo/configfiles/dreame.1c/','https://builder.dontvacuum.me/_dreame_mc1808.html','dreame.vacuum.mc1808.jpg','https://builder.dontvacuum.me/dreame/','Base station: CDZ1902',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,'CDZ1902',0,0);
INSERT INTO `robotinfo` VALUES (2,'dreame.vacuum.p2008','Dreame Robot Vacuum-Mop F9','Dreame',NULL,NULL,'p2008','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',2,2020,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2008/voices/soundpackage.json','n','y (1x SC031GS up facing[640x480])','y','y','n','n','4x + 1x',NULL,'IR bar','y (IR)','rubber+brush','3.5.8',NULL,'y','Q2/2020','y','y',NULL,'easy via UART, minimal teardown','https://dontvacuum.me/robotinfo/configfiles/dreame.f9/','https://builder.dontvacuum.me/_dreame_p2008.html','dreame.vacuum.p2008.jpg','https://builder.dontvacuum.me/dreame/',NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (3,'dreame.vacuum.p2009','Dreame Robot Vacuum D9','Dreame','RLS5',NULL,'p2009','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',256,'256 MByte',256,'256MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',4,2020,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2009/voices/soundpackage.json','y','n','y','y','n','y','6x','y','IR','n','rubber+brush','3.5.8',NULL,'y','Q4/2020','y','y',NULL,'easy via UART, minimal teardown',NULL,'https://builder.dontvacuum.me/_dreame_p2009.html','dreame.vacuum.p2009.jpg','https://builder.dontvacuum.me/dreame/','Base station: P2057\r\n\r\nIf you get a \"cat: can\'t open \'/etc/os_release\': No such file or directory\" message instead of a login shell, your Firmware version is too new. Create a ticket on https://vaers.dontvacuum.me/',NULL,NULL,0,0,NULL,'','',NULL,'','','B08HKYVRTG','B08HKYVRTG','',NULL,'2AXGD-RLS5','https://fccid.io/2AXGD-RLS5','P2057',0,0);
INSERT INTO `robotinfo` VALUES (4,'dreame.vacuum.p2027','Dreame Robot Vacuum W10','Dreame','RLS5C',NULL,'p2027','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',256,'256 MByte',256,'256MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',4,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2027/voices/soundpackage.json','y','n','y (rotating)','y','y (included, water change)','y','6x','y','IR','y (ultrasonic)','rubber+brush','4.1.6',NULL,'y','Q4/2021','y','y','https://dontvacuum.me/teardowns/dreame.vacuum.p2027/','easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2027.html','dreame.vacuum.p2027.jpg','https://builder.dontvacuum.me/dreame/',NULL,'<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'','','',NULL,'','B09994T1NB','B09QW4K2P6','',NULL,'2AXGD-RLS5C','https://fccid.io/2AXGD-RLS5C',NULL,0,1);
INSERT INTO `robotinfo` VALUES (5,'dreame.vacuum.p2028','Dreame Bot Z10 Pro','Dreame','RLS5D',NULL,'p2028','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',512,'512 MByte',512,'512MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',2,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2028/voices/soundpackage.json','y','y (1x SC031GS front facing [640x480] for linelaser)','y','y','y (included, dust collection)','n','6x','y','LineLaser','n','rubber+brush','4.1.2',NULL,'y','Q2/2021','y','y',NULL,'easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2028.html','dreame.vacuum.p2028.jpg','https://builder.dontvacuum.me/dreame/','Is the Dreame Z10 Pro recommended for purchase? Yes, check also the Dreame L10 Pro RootFS (sqfs) signed after 11/2021\r\n\r\nIf you get a \"cat: can\'t open \'/etc/os_release\': No such file or directory\" message instead of a login shell, your Firmware version is too new. Create a ticket on https://vaers.dontvacuum.me/','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,1,1,NULL,'https://www.amazon.com/dp/B09997J3W6?&linkCode=ll1&tag=wiseclab-20&linkId=8021eae7a39a18c9a7b93ca59e650ef9&language=en_US&ref_=as_li_ss_tl',NULL,NULL,NULL,'','B09997J3W6','','',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `robotinfo` VALUES (6,'dreame.vacuum.p2028','Dreame Bot Z10 Pro (110V)','Dreame',NULL,'US','p2028','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',512,'512 MByte',512,'512MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',1,'OpenWRT (custom Tina)','4.9.x',2,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2028/voices/soundpackage.json','y','y (1x SC031GS front facing [640x480] for linelaser)','y','y','y (included, dust collection)','n','6x','y','LineLaser','n','rubber+brush','4.1.2','dreame-iot','y','Q2/2021','y','y',NULL,'easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2028.html',NULL,'https://builder.dontvacuum.me/dreame/','WARNING: The base station is 110V only. Operation of the base station in a region with 220V will make the auto empty fan explode! Is the Dreame Z10 Pro recommended for purchase? Yes, check also the Dreame L10 Pro\r\n\r\nIf you get a \"cat: can\'t open \'/etc/os_release\': No such file or directory\" message instead of a login shell, your Firmware version is too new. Create a ticket on https://vaers.dontvacuum.me/','<strong style=\"color: red;\">WARNING: The base station is 110V only. Operation of the base station in a region with 220V will make the auto empty fan explode!</strong> <strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,1,1,NULL,'https://www.amazon.com/dp/B09997J3W6?&linkCode=ll1&tag=wiseclab-20&linkId=8021eae7a39a18c9a7b93ca59e650ef9&language=en_US&ref_=as_li_ss_tl',NULL,NULL,NULL,'','B09997J3W6','','',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `robotinfo` VALUES (7,'dreame.vacuum.p2029','Dreame Bot L10 Pro','Dreame','RL5SL',NULL,'p2029','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',512,'512 MByte',512,'512MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',1,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2029/voices/soundpackage.json','y','y (1x SC031GS front facing [640x480] for linelaser)','y','y','n','n','6x','y','LineLaser','n','rubber+brush','4.1.2','dreame-iot','y','Q2/2021','y','y','https://dontvacuum.me/teardowns/dreame.vacuum.p2029/','easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2029.html','dreame.vacuum.p2029.jpg','https://builder.dontvacuum.me/dreame/','Is the Dreame L10 Pro recommended for purchase? Yes, check also the Dreame Z10 Pro Base station: P2157 RootFS (sqfs) signed after 11/2021\r\n\r\nIf you get a \"cat: can\'t open \'/etc/os_release\': No such file or directory\" message instead of a login shell, your Firmware version is too new. Create a ticket on https://vaers.dontvacuum.me/','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'',NULL,NULL,NULL,'','B08YNDH84H','B0953JSB9M','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (8,'dreame.vacuum.p2041','Xiaomi Vacuum 1T','Dreame','STYTJ02ZHM','CN','p2041','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1 GByte',512,'512MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',4,2020,'firmwares/dreame.vacuum.p2041.html','https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2041/voices/soundpackage.json','n','y (1x SC031GS up facing [640x480], 1x ToF camera to the front[224x1558])','y','y','n','n','4x + 1x','y','ToF','y (IR)','rubber+brush','(4.1.2 + Security Chip)',NULL,'y','Q2/2021','y','y','https://dontvacuum.me/teardowns/dreame.vacuum.p2041/','easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2041.html','dreame.vacuum.p2041.jpg','https://builder.dontvacuum.me/dreame/','Device made for Mainland China region. Base station: CDZ1902','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,'CDZ1902',0,0);
INSERT INTO `robotinfo` VALUES (9,'dreame.vacuum.p2041o','Xiaomi Vacuum 2 Pro+','Dreame',NULL,NULL,'p2041','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1 GByte',512,'512MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',4,2020,'firmwares/dreame.vacuum.p2041.html','https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2041/voices/soundpackage.json','n','y (1x SC031GS up facing [640x480], 1x ToF camera to the front[224x1558])','y','y','n','n','4x + 1x','y','ToF','y (IR)','rubber+brush','(4.1.2 + Security Chip)',NULL,'y','Q2/2021','y','y','https://dontvacuum.me/teardowns/dreame.vacuum.p2041/','easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2041.html','dreame.vacuum.p2041.jpg','https://builder.dontvacuum.me/dreame/','Same device as Xiaomi 1T, but global model Base station: CDZ1902','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,'CDZ1902',0,0);
INSERT INTO `robotinfo` VALUES (10,'dreame.vacuum.p2114a','Xiaomi Robot Vacuum X10+','Dreame','B101GL',NULL,'r2213','enc(zip), signed, enc, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1 GByte',4096,'4GByte eMMC','GD32F303*ET6','RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','y (1x OV8856 front facing [RGB,8MP), 1x SC031GS line laser [640x480])','y (rotating)','y (in basestation)','y (included, water change, dust collection)','y','4x','y','Camera, Linelaser','y (ultrasonic)','rubber+brush','(4.3.3 + Security Chip)',NULL,'y','Q4/2022','n','y',NULL,'easy',NULL,NULL,'dreame.vacuum.p2114a.jpg',NULL,'WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!\r\n\r\nRoot was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,0,NULL,NULL,'https://www.amazon.de/Xiaomi-Saugroboter-Wischfunktion-Akkulaufzeit-Wassernachf%C3%BCllung/dp/B0BD5RZWTG?th=1&linkCode=ll1&tag=wiseclab-21&linkId=8225ba1089a2bf44778b86d635b06a64&language=de_DE&ref_=as_li_ss_tl',NULL,NULL,'','','B0BD5RZWTG','','y',NULL,NULL,NULL,1,1);
INSERT INTO `robotinfo` VALUES (11,'dreame.vacuum.p2148o','Mijia Robot Vacuum-Mop Ultra Slim','Dreame','STYTJ04ZHM','CN','p2148','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1 GByte',512,'512MByte NAND',NULL,NULL,0,'OpenWRT (custom Tina)','4.9.x',2,2021,NULL,NULL,'y',NULL,'y','y','y','n','4x +1x','n','ToF','y (IR)','rubber+brush','(4.1.2 + Security Chip)',NULL,'y','Q2/2021','y','y',NULL,'easy via UART and USB stick',NULL,'https://builder.dontvacuum.me/_dreame_p2148.html','dreame.vacuum.p2148o.jpg','https://builder.dontvacuum.me/dreame/','Device made for Mainland China region. Will not work easily outside of Mainland China. Not recommended to buy if you are in other regions.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (12,'dreame.vacuum.p2149o','Xiaomi Self-Cleaning Robot Vacuum-Mop Pro','Dreame',NULL,'CN','p2149','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1 GByte',512,'512MByte NAND','GD32F303*ET6','RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',1,2022,NULL,NULL,'y',NULL,'y','y','y (included, water change)','y','6x','y',NULL,NULL,'rubber+brush','(4.1.2 + Security Chip)',NULL,'y','Q2/2022','n','y',NULL,'easy, WIP',NULL,NULL,NULL,NULL,'Device made for Mainland China region. Will not work easily outside of Mainland China. Not recommended to buy if you are in other regions.\r\n\r\nRoot was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (13,'dreame.vacuum.p2156o','MOVA Z500 Robot Vacuum and Mop Cleaner','Dreame',NULL,NULL,'p2156','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',4,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2009/voices/soundpackage.json','n','y (1x SC031GS up facing[640x480])','y','y','n','n','4x','y','IR bar',NULL,'rubber+brush','3.5.8',NULL,'y','Q2/2021','y','y',NULL,'easy via UART, minimal teardown',NULL,'https://builder.dontvacuum.me/_dreame_p2156.html','dreame.vacuum.p2156o.jpg','https://builder.dontvacuum.me/dreame/','Device likely End-of-Life/End-of-Sale.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (14,'dreame.vacuum.p2187','Dreame Robot Vacuum D9 Pro','Dreame','RLS6L',NULL,'p2187','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',256,'256 MByte',256,'256MByte NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',2,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2187/voices/soundpackage.json','y','n','y','y','n','y','6x','y','IR',NULL,'rubber+brush','3.5.8',NULL,'y','Q3/2021','y','y',NULL,'easy via UART, minimal teardown',NULL,'https://builder.dontvacuum.me/_dreame_p2187.html','dreame.vacuum.p2187.jpg','https://builder.dontvacuum.me/dreame/','Device likely End-of-Life/End-of-Sale. Can be converted via Software to a D9.',NULL,NULL,1,0,NULL,'',NULL,NULL,NULL,'','B0978ZBZNK','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (15,'dreame.vacuum.p2259','Dreame Robot Vacuum D9 Max','Dreame',NULL,NULL,'p2259','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR112 (2x)',128,'128 MByte',128,'128MByte SPI NAND',NULL,NULL,0,'OpenWRT (custom Tina)','4.9.x',3,2021,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2009/voices/soundpackage.json','y','n','y','y','n','y',NULL,'y','IR',NULL,'rubber+brush','3.5.8',NULL,'y',NULL,'n','n',NULL,'will not run Valetudo due to resources',NULL,NULL,NULL,NULL,'Device likely End-of-Life/End-of-Sale. Device has relatively weak hardware (in comparison to cheaper D9 variants). Hardware too limited to run Valetudo or other custom software. Not recommended device if you ever plan to root! Base station: P2157','<strong style=\"color: red;\">Not recommended for purchase and rooting!</strong>',NULL,1,0,NULL,'','',NULL,'','','','B09B9TRPF4','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (16,'dreame.vacuum.r2104','Dreame Bot W10 Pro','Dreame',NULL,NULL,'r2104','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1024 MByte',8192,'8GByte eMMC','GD32F303*ET6','RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',1,2022,NULL,NULL,'y',NULL,'y','y','y (included, water change)','y',NULL,'y',NULL,NULL,'rubber+brush','4.1.2',NULL,'y',NULL,'n','n',NULL,'easy, WIP',NULL,NULL,'dreame.vacuum.r2104.jpg',NULL,'Root was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,0,NULL,NULL,'',NULL,NULL,'','','B0B4P1W3Q5','',NULL,NULL,NULL,NULL,0,1);
INSERT INTO `robotinfo` VALUES (17,'dreame.vacuum.r2216o','Dreame Bot L10S Pro','Dreame','RLS6L',NULL,'r2216','enc(zip), signed, enc, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR133 (4x)',512,'512 MByte',256,'256MByte NAND',NULL,'RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',4,2022,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.r2216o/voices/soundpackage.json','y','y (1x SC031GS front facing [640x480])','y','y','n','y','4x','y','LineLaser','y (ultrasonic)','rubber','4.1.2','dreame-iot','y','Q4/2022','y','y',NULL,'easy',NULL,'https://builder.dontvacuum.me/_dreame_r2216.html','dreame.vacuum.r2216o.jpg',NULL,'Despite the similar name, the hardware of the L10S Pro is way weaker than the L10S Ultra. Also, you cannot upgrade from the L10S Pro to Ultra by adding a station.\r\n\r\nRoot was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,0,NULL,NULL,'','','','','','B0BDXSS63Z','B0BDXSS63Z','y',NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (18,'dreame.vacuum.r2257o','DreameBot L10 Ultra','Dreame','RLS6LADC',NULL,'r2257','enc(2x), signed, sqfs(signed)',NULL,NULL,NULL,'Allwinner MR133 (4x)',512,'512 MByte',256,'256MByte NAND',NULL,'RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',4,2022,NULL,NULL,'y','n','y (rotating)','y (in basestation)','y (included, water change, dust collection)','y','4x','y','IR',NULL,'rubber+brush','4.3.3','dreame-iot','y','Q1/2023','y','y',NULL,NULL,NULL,'https://builder.dontvacuum.me/_dreame_r2257.html','dreame.vacuum.r2257.jpg',NULL,'WARNING: Device very weak hardware in comparison to L10s Ultra. Is missing many sensors, while looking similar. Dont get fooled. The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!','<strong style=\"color: red;\">Weak hardware, do not confuse with L10s Ultra</strong>',NULL,0,1,NULL,'','','','','','B0BTDKV1GS','B0BLYXDPMR','',NULL,NULL,NULL,NULL,1,1);
INSERT INTO `robotinfo` VALUES (19,'dreame.vacuum.r2228o','Dreame Robot L10S Ultra','Dreame','RLS6LADC',NULL,'p2228','enc(zip), signed, enc, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',1024,'1 GByte',4096,'4GByte eMMC',NULL,'RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,'https://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.r2228o/voices/soundpackage.json','y','y (1x OV8856 front facing [RGB,8MP), 1x SC031GS line laser [640x480])','y(rotating)','y (in basestation)','y (included, water change, dust collection)','y','4x','y','Camera, Linelaser','y (ultrasonic)','rubber','4.3.3','dreame-iot','y','Q4/2022','y','y',NULL,'easy',NULL,'https://builder.dontvacuum.me/_dreame_r2228.html','dreame.vacuum.r2228o.jpg','https://builder.dontvacuum.me/nextgen/','WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!\r\n\r\nRoot was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'https://www.amazon.com/Dreametech-Self-refilling-Self-Emptying-Navigation-Compatible/dp/B0B7J95MHN?linkCode=sl1&tag=wiseclab-20&linkId=0aa5978b904f251c269cd7f05a8e809b&language=en_US&ref_=as_li_ss_tl&th=1','https://www.amazon.de/dp/B0B8X43GQH?&linkCode=ll1&tag=wiseclab-21&linkId=3b3ea04c01a0ac38e86c92d8a23f3392&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0B8X43GQH?&linkCode=ll1&tag=wiseclab0e-21&linkId=90fcfa03d2495eb76eb944f08b561205&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/Dreame-Aspirapolvere-Lavapavimenti-Autopulente-Rilevamento/dp/B0B8X43GQH?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1KLQR1ZB36CNZ&keywords=Dreame%2BL10S%2BUltra&qid=1692904906&sprefix=dreame%2Bl10s%2Bultra%2Caps%2C129&sr=8-5&th=1&linkCode=sl1&tag=wiseclab0c-21&linkId=9917dc3e878a1b7444ae1c3408b8ed94&ref_=as_li_ss_tl','https://www.amazon.co.uk/Dreame-Self-Cleaning-Automatic-Collection-RLS6LADC-UK/dp/B0BG38TGXK?crid=21XP48RP24I5E&keywords=Dreame%2BL10S%2BUltra&qid=1692904483&s=kitchen&sprefix=dreame%2Bl10s%2Bultra%2Ckitchen%2C129&sr=1-3&ufe=app_do%3Aamzn1.fos.cc223b57-2b86-485c-a85e-6431c1f06c86&th=1&linkCode=sl1&tag=wiseclab00-21&linkId=94f059fe025846b58c413f2d284507f0&language=en_GB&ref_=as_li_ss_tl','B0B7J95MHN','B0B8X43GQH','B0BG38TGXK','y',NULL,NULL,NULL,1,1);
INSERT INTO `robotinfo` VALUES (20,'dreame.vacuum.r2205','Dreame Bot D10 Plus','Dreame',NULL,NULL,'r2205','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR112 (2x)',128,'128 MByte',256,'256MByte SPI NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','n','y','y','y (auto empty)','y',NULL,'y','IR','n','rubber','4.1.2','dreame-iot','y',NULL,'n','n',NULL,'will not run Valetudo due to resources',NULL,NULL,NULL,NULL,'Weak hardware. Do not confuse with D10s Plus or D10s Pro!','<strong style=\"color: red;\">Not recommended for purchase and rooting! Will likely never be supported for root/Valetudo</strong>',NULL,0,1,NULL,'https://www.amazon.com/dp/B09VKZT1FQ?&linkCode=ll1&tag=wiseclab-20&linkId=3271320bfc42427f543d8f6320576438&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/dp/B0B4P3H6K8?&linkCode=ll1&tag=wiseclab-21&linkId=c5d53c13e93e9bc8e3638eb921f2c0b7&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0B4P3H6K8?&linkCode=ll1&tag=wiseclab0e-21&linkId=f7a3f95981512a7ddefdb199ba41e28d&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/dp/B0B4P3H6K8?&linkCode=ll1&tag=wiseclab-20&linkId=977ba964c3725aca86bd9f0c588a0553&ref_=as_li_ss_tl','https://www.amazon.co.uk/dp/B0BG374SH3?&linkCode=ll1&tag=wiseclab-20&linkId=3abeb23eb860bf8ec228aa48ec54896b&ref_=as_li_ss_tl','B09VKZT1FQ','B0B4P3H6K8','B0BG374SH3',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `robotinfo` VALUES (21,'dreame.vacuum.r2205','Dreame Bot D10 Plus (110V)','Dreame',NULL,'US','r2205','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR112 (2x)',128,'128 MByte',256,'256MByte SPI NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',1,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','n','y','y','y (auto empty)','y',NULL,'y','IR','n','rubber','4.1.2','dreame-iot','y',NULL,'n','n',NULL,'will not run Valetudo due to resources',NULL,NULL,NULL,NULL,'WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode! Do not confuse this model with D10s Pro or D10s Plus!!!','<strong style=\"color: red;\">Not recommended for purchase and rooting! Will likely never be supported for root/Valetudo</strong>',NULL,0,1,NULL,'https://www.amazon.com/dp/B09VKZT1FQ?&linkCode=ll1&tag=wiseclab-20&linkId=3271320bfc42427f543d8f6320576438&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/dp/B0B4P3H6K8?&linkCode=ll1&tag=wiseclab-21&linkId=c5d53c13e93e9bc8e3638eb921f2c0b7&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0B4P3H6K8?&linkCode=ll1&tag=wiseclab0e-21&linkId=f7a3f95981512a7ddefdb199ba41e28d&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/dp/B0B4P3H6K8?&linkCode=ll1&tag=wiseclab-20&linkId=977ba964c3725aca86bd9f0c588a0553&ref_=as_li_ss_tl','https://www.amazon.co.uk/dp/B0BG374SH3?&linkCode=ll1&tag=wiseclab-20&linkId=3abeb23eb860bf8ec228aa48ec54896b&ref_=as_li_ss_tl','B09VKZT1FQ','B0B4P3H6K8','B0BG374SH3',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `robotinfo` VALUES (22,'dreame.vacuum.r2243','Dreame Bot D10s','Dreame',NULL,NULL,'r2243','enc(2x), signed, sqfs',NULL,'tar.gz, unsigned',NULL,'Allwinner MR112 (2x)',128,'128 MByte',256,'256MByte SPI NAND','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','n','y','y','n','y',NULL,'y','IR','n','rubber','4.1.2','dreame-iot','y',NULL,'n','n',NULL,'will not run Valetudo due to resources',NULL,NULL,NULL,NULL,NULL,'<strong style=\"color: red;\">Not recommended for purchase and rooting!</strong>',NULL,0,1,NULL,NULL,'','','','','','B0BKPT6GQH','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (23,'dreame.vacuum.r2250','Dreame Bot D10s Pro','Dreame','RLS6A',NULL,'r2250','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',512,'512 MByte',4096,'4GByte eMMC','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','y (1x OV8856 front facing [RGB,8MP))','y','y','n','n','6x','y','LineLaser','n','rubber',NULL,'dreame-iot','y','Q4/2022','y','y',NULL,'easy',NULL,'https://builder.dontvacuum.me/_dreame_r2250.html','dreame.vacuum.r2250.jpg','https://builder.dontvacuum.me/nextgen/','Root was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,'','https://www.amazon.com/dp/B0BWH67TQ6?&linkCode=ll1&tag=wiseclab-20&linkId=62dba85be65d7f1401c61fedd324fcf2&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/dp/B0BKGL6V9C?&linkCode=ll1&tag=wiseclab-21&linkId=2bcf29c1bf27d83e818427543314756c&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0BKGL6V9C?&linkCode=ll1&tag=wiseclab0e-21&linkId=679f351a6ad9a94b1650b57d242d9e18&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/dp/B0BKGL6V9C?&linkCode=ll1&tag=wiseclab-20&linkId=4cd20e1edb0cad57a8a9556b2c149490&ref_=as_li_ss_tl','https://www.amazon.co.uk/dp/B0BKGL6V9C/?&linkCode=ll1&tag=wiseclab-20&linkId=a9f4f59380778182da868e5d392870b5&language=en_GB&ref_=as_li_ss_tl','B0BWH67TQ6','B0BKGL6V9C','B0BKGL6V9C',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (24,'dreame.vacuum.r2240','Dreame Bot D10s Plus','Dreame','RLS6AD',NULL,'r2240','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',512,'512 MByte',4096,'4GByte eMMC','GD32F303*ET6','RTL8189FTV (6189N-SFC)',0,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','y (1x OV8856 front facing [RGB,8MP))','y','y','y (included, dust collection)','n','6x','y','LineLaser','n','rubber',NULL,'dreame-iot','y','Q4/2022','y','y',NULL,'easy',NULL,'https://builder.dontvacuum.me/_dreame_r2240.html','dreame.vacuum.r2240.jpg','https://builder.dontvacuum.me/nextgen/','WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,'','https://www.amazon.com/Dreametech-D10-Plus-Self-Emptying-Navigation/dp/B0BTYJ1W5B?th=1&linkCode=ll1&tag=wiseclab-20&linkId=6bd7325567cb4a784f5f7ca8df0a0edb&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/dp/B0BKGLJJT4?&linkCode=ll1&tag=wiseclab-21&linkId=ab648eb7ee273bd0152db3c00610a49e&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0BKGLJJT4?&linkCode=ll1&tag=wiseclab0e-21&linkId=8d7a35ded459d480946eb5ea88935e86&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/dp/B0BKGLJJT4?&linkCode=ll1&tag=wiseclab-20&linkId=9fca520b15d8bf87960dc550781de3c7&ref_=as_li_ss_tl','','B0BTYJ1W5B','B0BKGLJJT4','',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `robotinfo` VALUES (25,'dreame.vacuum.r2240','Dreame Bot D10s Plus (110V)','Dreame',NULL,'US','r2240','enc(2x), signed, sqfs(signed)',NULL,'tar.gz, unsigned',NULL,'Allwinner MR813 (4x)',512,'512 MByte',4096,'4GByte eMMC','GD32F303*ET6','RTL8189FTV (6189N-SFC)',1,'OpenWRT (custom Tina)','4.9.x',3,2022,NULL,NULL,'y','y (1x OV8856 front facing [RGB,8MP))','y','y','y (included, dust collection)','n','6x','y','LineLaser','n','rubber',NULL,'dreame-iot','y','Q4/2022','y','y',NULL,'easy',NULL,NULL,NULL,NULL,'WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!\r\n\r\nRoot was released at DEFCON 31. Root possible without breaking warranty seals.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,'','https://www.amazon.com/Dreametech-D10-Plus-Self-Emptying-Navigation/dp/B0BTYJ1W5B?th=1&linkCode=ll1&tag=wiseclab-20&linkId=6bd7325567cb4a784f5f7ca8df0a0edb&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/dp/B0BKGLJJT4?&linkCode=ll1&tag=wiseclab-21&linkId=ab648eb7ee273bd0152db3c00610a49e&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0BKGLJJT4?&linkCode=ll1&tag=wiseclab0e-21&linkId=8d7a35ded459d480946eb5ea88935e86&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/dp/B0BKGLJJT4?&linkCode=ll1&tag=wiseclab-20&linkId=9fca520b15d8bf87960dc550781de3c7&ref_=as_li_ss_tl','','B0BTYJ1W5B','B0BKGLJJT4','',NULL,NULL,NULL,NULL,1,0);
INSERT INTO `robotinfo` VALUES (26,'roborock.vacuum.a08','Roborock S6 Pure','Roborock',NULL,NULL,'rubysc1','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',512,'512MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',1,2020,'firmwares/roborock.vacuum.p5.html','https://awsde0.fds.api.xiaomi.com/rubysc1/app/voice-pkg/info','y','n','n','n','n','y','4x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q1/2020','y','y',NULL,'disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a08.html','roborock.vacuum.a08.jpg','https://builder.dontvacuum.me/howtos/s5e-cheatsheet.txt',NULL,NULL,NULL,1,0,NULL,NULL,'',NULL,NULL,'','','B085G2N2F7','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (27,'roborock.vacuum.a09','Roborock T7 Pro','Roborock',NULL,'CN','tanosv','enc, signed, header in TZ',NULL,NULL,NULL,'Qualcomm APQ8053 (8x)',512,'512 MByte',4096,'4GByte eMCP','STM32F103VCT6','Qualcomm',0,'Android','3.18.x',2,2020,NULL,'https://awsde0.fds.api.xiaomi.com/tanosv/app/voice-pkg/info','y','y (2x OV5695 front [1920x1080]) with IR illumination','y','y','n','y','6x','y','Cameras(+illum)','n','rubber+brush','3.5.8','tuya','y','Q2/2020','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.a10/','very hard (BGA soldering or ISP)',NULL,NULL,NULL,NULL,'Device made for Mainland China region. Will not work easily outside of Mainland China. Not recommended to buy if you are in other regions.','<strong style=\"color: red;\">Not recommended for purchase and rooting!</strong>',NULL,0,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (28,'roborock.vacuum.a10','Roborock S6 MaxV','Roborock',NULL,NULL,'tanosv','enc, signed, header in TZ',NULL,NULL,NULL,'Qualcomm APQ8053 (8x)',512,'512 MByte',4096,'4GByte eMCP','STM32F103VCT6','Qualcomm',0,'Android','3.18.x',2,2020,NULL,'https://awsde0.fds.api.xiaomi.com/tanosv/app/voice-pkg/info','y','y (2x OV5695 front [1920x1080]) with IR illumination','y','y','n','y','6x','y','Cameras(+illum)','n','rubber+brush','3.5.8','tuya','y','Q2/2020','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.a10/','very hard (BGA soldering or ISP)',NULL,NULL,NULL,'https://www.youtube.com/watch?v=EWqFxQpRbv8','Root very difficult and not doable for most people. Stay away from this device if you ever want to use it without cloud.','<strong style=\"color: red;\">Not recommended for purchase and rooting!</strong>',NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','B084Z5JD5Q','B08DHWLZSR','','y','2AN20-S6MAXV','https://fccid.io/2AN2O-S6MAXV','S6V51-01, CDZ11RR',0,0);
INSERT INTO `robotinfo` VALUES (29,'roborock.vacuum.a11','Roborock T7','Roborock',NULL,'CN','tanose','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',512,'512MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',1,2020,NULL,'https://awsde0.fds.api.xiaomi.com/tanose/app/voice-pkg/info','y','n','y','y','n','n','6x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q1/2020','y','y',NULL,'disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a11.html',NULL,NULL,NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (30,'roborock.vacuum.a14','Roborock T7S','Roborock',NULL,'CN','tanoss','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.5.x',1,2021,NULL,'https://awsde0.fds.api.xiaomi.com/tanoss/app/voice-pkg/info','y','n','y','y','y (separate)','y','4x','y','IR','y (ultrasonic)','rubber','4.1.2','tuya','y','Q1/2021','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.a15/','disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a15.html',NULL,NULL,'Device made for Mainland China region.',NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (31,'roborock.vacuum.a15','Roborock S7','Roborock',NULL,NULL,'tanoss','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.5.x',1,2021,NULL,'https://awsde0.fds.api.xiaomi.com/tanoss/app/voice-pkg/info','y','n','y (vibrating)','y','y (seperate)','y','4x','y','IR','y (ultrasonic)','rubber','4.1.2','tuya','y','Q1/2021','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.a15/','disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a15.html','roborock.vacuum.a15.jpg',NULL,'+ (plus) variant has auto empty base station',NULL,NULL,0,1,NULL,'','',NULL,NULL,'','B08VHZJ6R2','B097DGLM1V','',NULL,'2AN2O-TSW05','https://fccid.io/2AN2O-TSW05',NULL,2,0);
INSERT INTO `robotinfo` VALUES (32,'roborock.vacuum.a19','Roborock S4 Max','Roborock',NULL,NULL,NULL,'enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',4,2020,NULL,'https://builder.dontvacuum.me/pkg/voice/roborock/','y','n','n','n','n','y','4x','y','IR','n','rubber+brush','4.1.2','tuya','y','Q4/2020','y','y',NULL,'disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a19.html','roborock.vacuum.a19.jpg','https://builder.dontvacuum.me/howtos/s5e-cheatsheet.txt',NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (33,'roborock.vacuum.m1s','Xiaomi Vacuum Robot 1S','Roborock','SDJQR03RR','CN','ruby2','enc, sign, header in TZ',NULL,'A=enc, signed','use S6 Voices as alternative','Rockchip RK3326 (4x)',512,'512 MByte',4096,'4Gbyte eMMC','STM32F103VET6','RTL8189ETV',0,'Linux','4.4.x',2,2019,NULL,'https://awsde0.fds.api.xiaomi.com/ruby2/app/voice-pkg/info','y','y (1x OV7251 up facing[640x480])','n','n','n','n','4x','y','n','n','rubber+brush','3.5.8',NULL,'y','Q2/2019','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.m1s/','very hard (BGA soldering or ISP)',NULL,NULL,'roborock.vacuum.m1s.jpg','https://www.youtube.com/watch?v=EWqFxQpRbv8','Root very difficult and not doable for most people. Stay away from this device if you ever want to use it without cloud.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (34,'roborock.vacuum.p5','Roborock P5','Roborock',NULL,'CN','rubysc1','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',512,'512MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',4,2019,'firmwares/roborock.vacuum.p5.html','https://awsde0.fds.api.xiaomi.com/rubysc1/app/voice-pkg/info','y','n','n','n','n','y','4x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q1/2020','y','y',NULL,'disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a08.html',NULL,'https://builder.dontvacuum.me/howtos/s5e-cheatsheet.txt',NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (35,'roborock.vacuum.s4','Roborock S4','Roborock',NULL,NULL,'rubyplus','enc(AES-256-CBC), signed (RSA)',NULL,'A=enc, signed',NULL,'Allwinner R16 (4x)',512,'512 MByte',4096,'4GByte eMMC','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',3,2018,'firmwares/roborock.vacuum.s4.html','https://awsde0.fds.api.xiaomi.com/rubyplus/app/voice-pkg/info','y','n','y','n','n','n','4x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q3/2019','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.x4/','disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/roborock.s4/','https://builder.dontvacuum.me/_s4.html','roborock.vacuum.s4.jpg','https://builder.dontvacuum.me/howtos/x6cheatsheet.txt',NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (36,'roborock.vacuum.s5','Roborock S5 / S50','Roborock','S50',NULL,'rubys','ccrypt, unsigned',NULL,'ccrypt, unsigned',NULL,'Allwinner R16 (4x)',512,'512 MByte',4096,'4GByte eMMC','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',4,2017,'firmwares/roborock.vacuum.s5.html','https://cnbj2.fds.api.xiaomi.com/rubys/app/voice-pkg/info','y','n','y','n','n','y','4x','y','IR','n','rubber+brush','3.3.9, 3.5.8',NULL,'y','Q1/2018','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.s5/','fw < v2020: easy, else: disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/roborock.s5/','https://builder.dontvacuum.me/_s5.html','roborock.vacuum.s5.jpg',NULL,'Device likely End-of-Life/End-of-Sale. Factory firmware on the device likely is rootable remotely.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,'2AN2O-RS001','https://fccid.io/2AN2O-RS001',NULL,0,0);
INSERT INTO `robotinfo` VALUES (37,'roborock.vacuum.s5e','Roborock S5 Max','Roborock','S5E02-00',NULL,'rubyslite','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',512,'512MByte NAND','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',4,2019,NULL,'https://awsde0.fds.api.xiaomi.com/rubyslite/app/voice-pkg/info','y','n','y','y','n','n','4x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q1/2020','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.s5e/','disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/roborock.s5e/','https://builder.dontvacuum.me/_s5e.html','roborock.vacuum.s5e.jpg','https://builder.dontvacuum.me/howtos/s5e-cheatsheet.txt',NULL,NULL,NULL,0,0,NULL,'',NULL,NULL,NULL,'','B07ZNJ6Q9X','B087716TNX','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (38,'roborock.vacuum.s5e','Roborock S5 Max','Roborock',NULL,NULL,'rubyslite','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND','STM32F103VCT6','RTL8189ETV',1,'Ubuntu 14.04','3.4.x',2,2020,NULL,'https://awsde0.fds.api.xiaomi.com/rubyslite/app/voice-pkg/info','y','n','y','y','n','y','4x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q1/2020','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.s5e/','disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/roborock.s5e/','https://builder.dontvacuum.me/_s5e.html',NULL,'https://builder.dontvacuum.me/howtos/s5e-cheatsheet.txt',NULL,NULL,NULL,0,0,NULL,'',NULL,NULL,NULL,'','B07ZNJ6Q9X','B087716TNX','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (39,'roborock.vacuum.s6','Roborock S6','Roborock',NULL,NULL,'tanos','enc(AES-256-CBC), signed (RSA)',NULL,'A=enc, signed',NULL,'Allwinner R16 (4x)',512,'512 MByte',4096,'4GByte eMMC','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',2,2018,'firmwares/roborock.vacuum.s6.html','https://awsde0.fds.api.xiaomi.com/tanos/app/voice-pkg/info','y','n','y','n','n','y','6x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q2/2019','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.x6/','disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/roborock.s6/','https://builder.dontvacuum.me/_s6.html','roborock.vacuum.s6.jpg','https://builder.dontvacuum.me/howtos/x6cheatsheet.txt',NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','B07RYBT3DN','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (40,'roborock.vacuum.t4','Roborock T4','Roborock',NULL,'CN','rubyplus','enc(AES-256-CBC), signed (RSA)',NULL,'A=enc, signed',NULL,'Allwinner R16 (4x)',512,'512 MByte',4096,'4GByte eMMC','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',3,2018,'firmwares/roborock.vacuum.s4.html','https://awsde0.fds.api.xiaomi.com/rubyplus/app/voice-pkg/info','y','n','y','n','n','n','4x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q3/2019','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.x4/','disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_s4.html',NULL,'https://builder.dontvacuum.me/howtos/x6cheatsheet.txt','Device made for Mainland China region. Will not work easily outside of Mainland China. Not recommended to buy if you are in other regions.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (41,'roborock.vacuum.t6','Roborock T6','Roborock','R61RR','CN','tanos','enc(AES-256-CBC), signed (RSA)',NULL,'A=enc, signed',NULL,'Allwinner R16 (4x)',512,'512 MByte',4096,'4GByte eMMC','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',2,2018,'firmwares/roborock.vacuum.s6.html','https://awsde0.fds.api.xiaomi.com/tanos/app/voice-pkg/info','y','n','y','n','n','y','6x','y','IR','n','rubber+brush','3.5.8','tuya','y','Q2/2019','y','y','https://dontvacuum.me/teardowns/roborock.vacuum.x6/','disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/roborock.t6/','https://builder.dontvacuum.me/_s6.html',NULL,'https://builder.dontvacuum.me/howtos/x6cheatsheet.txt','Device made for Mainland China region. Will not work easily outside of Mainland China. Not recommended to buy if you are in other regions.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (42,'rockrobo.vacuum.v1','Xiaomi Vacuum Robot','Roborock',NULL,NULL,'ruby','ccrypt, unsigned',NULL,'ccrypt, unsigned',NULL,'Allwinner R16 (4x)',512,'512 MByte',4096,'4GByte eMMC','STM32F103VCT6','RTL8189ETV',0,'Ubuntu 14.04','3.4.x',3,2016,NULL,'http://builder.dontvacuum.me/pkg/voice/rockrobo/voice-v1/','y','n','n','n','n','n','4x','y','Ultrasonic','n','rubber+brush','3.3.9, 3.5.8',NULL,'y','Q4/2017','y','y','https://dontvacuum.me/teardowns/rockrobo.vacuum.v1/','fw < v4004: easy, else: disassembly, simple soldering','https://dontvacuum.me/robotinfo/configfiles/rockrobo.v1/','https://builder.dontvacuum.me/_v1.html','v1.jpg',NULL,NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (43,'viomi.vacuum.v6','Viomi V2','3irobotics',NULL,NULL,'CRL-200S','zip, sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',2,2019,NULL,'https://builder.dontvacuum.me/pkg/voice/viomi','y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush','3.5.8','viomi-iot','y','Q2/2019','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','old fw: easy via usb-adb, new fw: disassembly','https://dontvacuum.me/robotinfo/configfiles/viomi.v6/','https://builder.dontvacuum.me/_viomi_v6.html','viomi.vacuum.v6.jpg','https://github.com/Hypfer/valetudo-crl200s-root','Device likely End-of-Life/End-of-Sale. It is a OEM product of 3irobotics that was modified by Viomi.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (44,'viomi.vacuum.v7','Mi Robot Vacuum-Mop P','3irobotics','STYTJ02YM','CN','CRL-200S','zip, sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',2,2019,NULL,'https://builder.dontvacuum.me/pkg/voice/viomi','y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush','3.5.8',NULL,'y','Q2/2019','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','old fw: easy via usb-adb, new fw: disassembly','https://dontvacuum.me/robotinfo/configfiles/viomi.v7/','https://builder.dontvacuum.me/_viomi_v7.html','viomi.vacuum.v7.jpg','https://github.com/Hypfer/valetudo-crl200s-root','Device likely End-of-Life/End-of-Sale. It is a OEM product of 3irobotics that was modified by Viomi.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (45,'viomi.vacuum.v8','Mi Robot Vacuum-Mop P','3irobotics','STYJ02YM',NULL,'CRL-200S','zip, sqfs, encrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',3,2019,NULL,'https://builder.dontvacuum.me/pkg/voice/viomi','y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush','3.5.8',NULL,'y','Q2/2019','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','old fw: easy via usb-adb, new fw: disassembly','https://dontvacuum.me/robotinfo/configfiles/viomi.v8/','https://builder.dontvacuum.me/_viomi_v7.html',NULL,'https://github.com/Hypfer/valetudo-crl200s-root','Device likely End-of-Life/End-of-Sale. It is a OEM product of 3irobotics that was modified by Viomi.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (46,'wyze.robot','Wyze Robot Vacuum','3irobotics','WVCR200S','US','WYZECRL20S (CRL-200S)','sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',4,2020,NULL,NULL,'y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush',NULL,'wyze-iot','y','Q1/2021','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','easy via usb-adb',NULL,NULL,NULL,NULL,'This robot is a clone of the Viomi V2 robot. It is a OEM product of 3irobotics that was modified.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (47,'conga.3290','Conga 3290','3irobotics','_05415','India','CECOTECCRL20D(CRL-200S)','sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',4,2019,NULL,NULL,'y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush',NULL,'conga-iot','y','Q4/2020','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','easy via usb-adb',NULL,'https://builder.dontvacuum.me/_3i_CRL200.html',NULL,'https://github.com/Hypfer/valetudo-crl200s-root','This robot is a clone of the Viomi V2 robot. It is a OEM product of 3irobotics that was modified.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (48,'conga.3790','Conga 3790','3irobotics','_05436','Spain','CECOTECCRL20S(CRL-200S)','sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8821CS',0,'OpenWRT','3.4.x',4,2019,NULL,NULL,'y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush',NULL,'conga-iot','y','Q4/2020','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','easy via usb-adb',NULL,'https://builder.dontvacuum.me/_3i_CRL200.html',NULL,'https://github.com/Hypfer/valetudo-crl200s-root','This robot is a clone of the Viomi V2 robot. It is a OEM product of 3irobotics that was modified. It uses a different, 5Ghz-capable wifi module!',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (49,'proscenic.m6pro','Proscenic M6 Pro','3irobotics','LDS M6 PRO',NULL,'PSNKCRL20S(CRL-200S)','sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',4,2019,NULL,NULL,'y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush',NULL,'conga-iot','y','Q4/2020','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','easy via usb-adb',NULL,'https://builder.dontvacuum.me/_3i_CRL200.html',NULL,'https://github.com/Hypfer/valetudo-crl200s-root','This robot is a clone of the Viomi V2 robot. It is a OEM product of 3irobotics that was modified.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (50,'conga.3090','Conga 3090','3irobotics',NULL,NULL,'CECOTECCRL20A(CRL-200S)','sqfs, unencrypted',NULL,NULL,NULL,'Allwinner A33 (4x)',512,'512 MByte',256,'256MByte NAND','GD32F103VCT6','RTL8189ETV',0,'OpenWRT','3.4.x',4,2019,NULL,NULL,'y','n','y','y (replaces dustbin)','n','n','4x',NULL,'IR','n','rubber+brush',NULL,'conga-iot','y','Q4/2020','y','y','https://dontvacuum.me/teardowns/viomi-vacuum/','easy via usb-adb',NULL,'https://builder.dontvacuum.me/_3i_CRL200.html',NULL,'https://github.com/Hypfer/valetudo-crl200s-root','This robot is a clone of the Viomi V2 robot. It is a OEM product of 3irobotics that was modified.',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (51,'roborock.vacuum.a27','Roborock S7 MaxV','Roborock','S270RR',NULL,'TopazSV','enc, signed, header in TZ',NULL,NULL,NULL,'JLQ JA308 (4xA55)',1024,'1 GByte (DDR4)',8192,'8GByte eMMC','NATION N32G455VEL7','FN-Link SV6158',0,'Android','4.16.61',2,2022,'firmwares/roborock.vacuum.a27.html',NULL,'y','y (2x OV5695 front [1920x1080]) with IR illumination, 1x linelaser','y','y','y (optional)','y','6x','y','Cameras (+illum),Linelaser','n','rubber+brush','4.1.5','rriot','y','Q4/2022','n','y',NULL,'nearly unrootable, ARTHRP-2ex',NULL,NULL,NULL,NULL,'Stay away from this device if you ever want to use it without cloud. Unlikely to be rootable by endusers (that’s you!). Different base stations exist','<strong style=\"color: red;\">Not recommended for purchase and rooting!</strong>',NULL,0,1,NULL,'','',NULL,NULL,'','B09NM549V7','B09VTMJ2ZP','','y',NULL,NULL,NULL,2,2);
INSERT INTO `robotinfo` VALUES (52,'roborock.vacuum.a26','Roborock G10S Pro','Roborock',NULL,'CN','TopazSV','enc, signed, header in TZ',NULL,NULL,NULL,'JLQ JA308 (4xA55)',1024,'1 GByte (DDR4)',8192,'8GByte eMMC','NATION N32G455VEL7','FN-Link SV6158',0,'Android','4.16.61',2,2022,'firmwares/roborock.vacuum.a27.html',NULL,'y','y (2x OV5695 front [1920x1080]) with IR illumination, 1x linelaser','y','y','y (optional)','y','6x','y','Cameras (+illum),Linelaser','n','rubber+brush','4.1.5','rriot','y','Q4/2022','n','y',NULL,'nearly unrootable, ARTHRP-2ex',NULL,NULL,NULL,NULL,'Same as Roborock S7 MaxV. Device made for Mainland China region. Will not work easily outside of Mainland China. Not recommended to buy if you are in other regions. Stay away from this device if you ever want to use it without cloud.','<strong style=\"color: red;\">Not recommended for purchase and rooting!</strong>',NULL,0,1,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (53,'roborock.vacuum.a38','Roborock Q7 Max','Roborock','Q38DRR',NULL,'TanosSLite','enc(AES-256-CBC), signed (RSA), sqfs',NULL,'B=enc, signed, sqfs, ogg',NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND','NATION N32G455VEL7','Hi3881',0,'Ubuntu 14.04','3.4.x',1,2022,NULL,NULL,'y','n','y','y','y (auto empty with optional dock+)','y','4x','y','IR','n','rubber','4.1.5','tuya','y','Q2/2022','y','y',NULL,'disassembly, simple soldering',NULL,'https://builder.dontvacuum.me/_a38.html','roborock.vacuum.a38.jpg','https://builder.dontvacuum.me/howtos/s5e-cheatsheet.txt','+ (plus) variant has auto empty base station.\r\nDevices made for Mainland China region will not work easily outside of Mainland China. Not recommended to buy if you are in other regions (e.g. in Russia importing from China)\r\nGlobal devices should work just fine.',NULL,NULL,0,1,NULL,'','','','','','B09NNFNWZ9','B09SPCGRTX','',NULL,NULL,NULL,NULL,2,0);
INSERT INTO `robotinfo` VALUES (54,'ecovacs.2o4lnm','Ecovacs X1 Turbo','Ecovacs',NULL,NULL,'ZJ2102','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)',1024,'1 GByte (DDR4)',512,'512MByte SPI-NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',2,2022,NULL,NULL,'y','y','y (rotating)','y','y (mop cleaning)','y','6x','y','Cameras,Linelaser','y (ultrasonic)','rubber+brush',NULL,'ecovacs','y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html','Has Microphone. Has 2 sidebrushes. Same robot as X1 Omni, but different base station','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'','','',NULL,'','B09NPM632Z','B09PN27KTJ','','y','2AZAT-DEX11','https://fccid.io/2AZAT-DEX11/','CH2018',0,1);
INSERT INTO `robotinfo` VALUES (55,'ecovacs.1vxt52','Ecovacs X1 Omni','Ecovacs',NULL,NULL,'ZJ2102','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)',1024,'1 GByte (DDR4)',512,'512MByte SPI-NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',2,2022,NULL,NULL,'y','y','y (rotating)','y','y (included, water change, dust collection)','y','6x','y','Cameras,Linelaser','y (ultrasonic)','rubber+brush',NULL,'ecovacs','y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,'ecovacs.zj2102.jpg','https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html','Has Microphone. Has 2 sidebrushes. Same robot as X1 Turbo, but different base station. WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'','','',NULL,'','B09NPKWDRX','B09PFYMR3V','','y','2AZAT-DEX11','https://fccid.io/2AZAT-DEX11/','CH2013',1,1);
INSERT INTO `robotinfo` VALUES (56,'narwal.freo','Narwal Freo','Narwal','YJCC012',NULL,NULL,'signed, encrypted',NULL,NULL,NULL,'Allwinner MR813 (4x)',1024,'1 GByte',4096,'4GByte eMMC','GD32F303*ET6','RTL8723DS(BT+WiFi)',0,'OpenWRT (custom Tina)','4.9.x',4,2022,NULL,NULL,'y','n','y (rotating)','y (in basestation)','y (included, water change, dust collection)','y','4x','y','IR','y (ultrasonic)','rubber+brush',NULL,'narwal',NULL,NULL,'n','n',NULL,NULL,NULL,NULL,'narwal.freo.jpg',NULL,'Communication with base: Zigbee 3.0',NULL,NULL,0,1,NULL,'',NULL,NULL,NULL,'','B0B4D99WGK','','',NULL,NULL,NULL,NULL,0,1);
INSERT INTO `robotinfo` VALUES (57,'ecovacs.yna5xi','Ecovacs Ozmo 950','Ecovacs',NULL,NULL,'ZJ1816','encrypted',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'Linux',NULL,NULL,2019,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q2/2019','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (58,'ecovacs.ls1ok3','Ecovacs Deebot 900','Ecovacs',NULL,NULL,'ZJ1711','encrypted',NULL,NULL,NULL,'Rockchip RV1107 (1x)',128,'128 Mbyte (DDR3)',NULL,NULL,NULL,NULL,0,NULL,NULL,3,2018,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q3/2018','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (59,'ecovacs.x5d34r','Ecovacs T8 AIVI','Ecovacs','DLX11-55',NULL,'ZJ1913','encrypted',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'Linux (+ROS)',NULL,4,2021,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,0,1,NULL,'',NULL,NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (60,'ecovacs.36xnxf','Ecovacs N8','Ecovacs',NULL,NULL,'ZJ1921','encrypted',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,'Linux',NULL,4,2021,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,0,1,NULL,NULL,'',NULL,NULL,'','','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (61,'ecovacs.b742vd','Ecovacs T8','Ecovacs',NULL,NULL,'ZJ1921','encrypted',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,'ecovacs','y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,0,1,NULL,'',NULL,NULL,NULL,'','B08CSVDHTR','','',NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (63,'ecovacs.jtmf04','Ecovacs T10 Omni','Ecovacs',NULL,NULL,'ZJ2209','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)',1024,'1 GByte (DDR4)',256,'512MByte SPI-NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',1,2023,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q3/2023','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,0,1,NULL,'','',NULL,NULL,'','','','',NULL,'2AZAT-DBX53','https://fccid.io/2AZAT-DBX53','CH2208',1,1);
INSERT INTO `robotinfo` VALUES (64,'ecovacs.rss8xk','Ecovacs T10 Plus','Ecovacs',NULL,NULL,'ZJ2113','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)',1024,'1 GByte (DDR4)',512,'512MByte SPI-NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',1,2023,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,0,1,NULL,NULL,'',NULL,NULL,'','','B09T6NMQSN','',NULL,'2AZAT-DBX33','https://fccid.io/2AZAT-DBX33','CH2117',1,0);
INSERT INTO `robotinfo` VALUES (65,'ecovacs.n4gstt','Evovacs X1 Plus','Ecovacs',NULL,NULL,'ZJ2115','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)',1024,'1 GByte (DDR4)',512,'512MByte SPI-NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',3,2022,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'rubber+brush',NULL,NULL,'y','Q3/2022','y','n',NULL,'easy (UART)',NULL,NULL,NULL,'https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html',NULL,NULL,NULL,0,1,NULL,NULL,'',NULL,NULL,'','','B09TVB3T4J','',NULL,'2AZAT-DEX55','https://fccid.io/2AZAT-DEX55','CH2117',1,0);
INSERT INTO `robotinfo` VALUES (67,'roborock.vacuum.a70','Roborock S8 Pro Ultra','Roborock','S81USP',NULL,'Ultron-S Plus','enc, signed, header in TZ',NULL,NULL,NULL,'Allwinner MR813 (4x)',1024,'1 GByte (DDR4)',4096,'4GByte eMMC','GD32F303VCT6A','RT8189FS',0,'OpenWRT (custom Tina)','4.9.x',1,2023,NULL,NULL,'y','y (SC035HGS, OV7251, both front-facing) with IR illumination','y (vibrating)','y','y (included, water change, dust collection)','y','6x','2x','Cameras (+illum),Linelaser','y (ultrasonic)','dual rubber','4.3.5','rriot','y','04/2023','y','y','https://karlquinsland.com/roborock-s8-pro-ultra-dock-teardown/','medium (partial disassembly)',NULL,'https://builder.dontvacuum.me/_a70.html',NULL,'https://builder.dontvacuum.me/nextgen/','Base station is voltage dependent. Do not use a US 110V base station in a 220V country. Root was released at DEFCON 31. Root possible without breaking warranty seals.',NULL,NULL,0,1,NULL,'https://www.amazon.com/dp/B0BR5CGY21?linkCode=sl1&tag=wiseclab-20&linkId=15ff64442437abcceca876b8440c6f7d&language=en_US&ref_=as_li_ss_tl&th=1','https://www.amazon.de/roborock-Ultra-Selbstnachfuillend-Roboterstaubsauge-3D-Hindernisumgehung/dp/B0BSL98D73?th=1&linkCode=ll1&tag=wiseclab-21&linkId=1ac0b78d11d8a37dd7fdaf76fc15c4da&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/roborock-Pro-Ultra-Automatique-Remplissage/dp/B0BSL98D73?&linkCode=ll1&tag=wiseclab0e-21&linkId=c4a6a785c834a94fec7ba9b72d55fb8b&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/roborock-Pro-Ultra-Aspirapolvere-Lavapavimenti/dp/B0BSL98D73?&linkCode=ll1&tag=wiseclab0c-21&linkId=ef767bfeae4513c5831ed68d5d88198a&language=it_IT&ref_=as_li_ss_tl','','B0BVB5PTDK','B0BSL98D73','',NULL,'2AN2O-S81USP01','https://fccid.io/2AN2O-S81USP01',NULL,1,1);
INSERT INTO `robotinfo` VALUES (68,'roborock.vacuum.a51','Roborock S8','Roborock','S80ULT',NULL,'ULTRON-SOUTH','enc, signed, header in TZ',NULL,NULL,NULL,'Allwinner MR813 (4x)',1024,'1 GByte (DDR4)',4096,'4GByte eMMC','GD32F303VCT6A','RT8189FS',0,'OpenWRT (custom Tina)','4.9.x',1,2023,NULL,NULL,'y','y (SC035HGS, OV7251, both front-facing) with IR illumination','y (vibrating)','y','y (optional dust collection+)','y','6x','y','Cameras (+illum),Linelaser','y (ultrasonic)','dual rubber','4.3.5','rriot','y','04/2023','y','y',NULL,'medium (partial disassembly)',NULL,'https://builder.dontvacuum.me/_a51.html','roborock.vacuum.a51.jpg','https://builder.dontvacuum.me/nextgen/','+ (plus) variant has auto empty base station. Base station is voltage dependent. Do not use a US 110V base station in a 220V country. Root was released at DEFCON 31. Root possible without breaking warranty seals.',NULL,NULL,0,1,NULL,'https://www.amazon.com/dp/B0BR5CGYKY?&linkCode=ll1&tag=wiseclab-20&linkId=defed598098a9ed61a05cc96276d31d4&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/roborock-Wischroboter-Absaugstation-Auto-Lifting-Wischsystem-Sprachsteuerung/dp/B0C5FFH7FM?th=1&linkCode=ll1&tag=wiseclab-21&linkId=827a805ea525d2ffacdf238627d55702&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/Roborock-S8-Schwarz-Saug-Wisch-Roboter-Absaugstation/dp/B0BYXM5ZNQ?&linkCode=ll1&tag=wiseclab0e-21&linkId=e030bf49f74268ae7504a81b5b17ee07&language=fr_FR&ref_=as_li_ss_tl','','','B0BR5CGYKY','B0C5FFH7FM','B0BZ3MLRZ9',NULL,'2AN2O-S80ULT01','https://fccid.io/2AN2O-S80ULT01/','CDZ12RR',2,0);
INSERT INTO `robotinfo` VALUES (69,'roborock.vacuum.a62','Roborock S7 Pro Ultra','Roborock','S300RR',NULL,'TopazS','enc(AES-256-CBC), signed (RSA), sqfs',NULL,NULL,NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND',NULL,'Hi3881',0,'Ubuntu 14.04','3.4.x',3,2022,NULL,NULL,'y','n','y','y','y (included, water change, dust collection)','y','6x','2x','IR','y (ultrasonic)','rubber','4.1.8','rriot','y','01/2023','y','y',NULL,'teardown required',NULL,'https://builder.dontvacuum.me/_a62.html','roborock.vacuum.a62.jpg',NULL,NULL,NULL,NULL,0,1,NULL,NULL,'https://www.amazon.de/dp/B09YYJFKTS?&linkCode=ll1&tag=wiseclab-21&linkId=b4c5bb1d0c69b721318273d894d75f4c&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/dp/B0C2HR8JW3?th=1&linkCode=ll1&tag=wiseclab0e-21&linkId=3bd8cfb9ad44c6aa0ec3c8b82fd9917d&ref_=as_li_ss_tl','','','','B09YYJFKTS','',NULL,'2AN2O-S300RR01','https://fccid.io/2AN2O-S300RR01','EWFD01HRR, EWFD02HRR, WFD01HRR',1,1);
INSERT INTO `robotinfo` VALUES (70,'ecovacs.p1jij8','Ecovacs T20 Omni','Ecovacs',NULL,NULL,'ZJ2231','encrypted',NULL,NULL,NULL,'Rockchip RK3326 (4x)',512,'512 MByte RAM',512,'512MByte NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',2,2023,NULL,NULL,'y','y','y (rotating)','y','y (included, water change, dust collection)','y','6x','y','Linelaser','y (ultrasonic)','rubber+brush',NULL,'ecovacs','y','Q3/2023','y','n',NULL,'easy (UART)',NULL,NULL,'','https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html','Has Microphone. Has 2 sidebrushes. Same robot as T20 Turbo, but different base station. Camera cannot be used for live viewing. WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'','','',NULL,'','','','','y','','','',1,1);
INSERT INTO `robotinfo` VALUES (71,'roborock.vacuum.a70','Roborock S8 Pro Ultra','Roborock','S81USP',NULL,'Ultron-S Plus','enc, signed, header in TZ',NULL,NULL,NULL,'Allwinner MR813 (4x)',512,'512 MByte (DDR4)',4096,'4GByte eMMC','GD32F303VCT6A','RT8189FS',1,'OpenWRT (custom Tina)','4.9.x',1,2023,NULL,NULL,'y','y (SC035HGS, OV7251, both front-facing) with IR illumination','y (vibrating)','y','y (included, water change, dust collection)','y','6x','2x','Cameras (+illum),Linelaser','y (ultrasonic)','dual rubber','4.3.5','rriot','y','04/2023','y','y','https://karlquinsland.com/roborock-s8-pro-ultra-dock-teardown/','medium (partial disassembly)',NULL,'https://builder.dontvacuum.me/_a70.html','roborock.vacuum.a70.jpg','https://builder.dontvacuum.me/nextgen/','Base station is voltage dependent. Do not use a US 110V base station in a 220V country. Root was released at DEFCON 31. Root possible without breaking warranty seals.',NULL,NULL,0,1,NULL,'https://www.amazon.com/dp/B0BR5CGY21?linkCode=sl1&tag=wiseclab-20&linkId=15ff64442437abcceca876b8440c6f7d&language=en_US&ref_=as_li_ss_tl&th=1','https://www.amazon.de/roborock-Ultra-Selbstnachfuillend-Roboterstaubsauge-3D-Hindernisumgehung/dp/B0BSL98D73?th=1&linkCode=ll1&tag=wiseclab-21&linkId=1ac0b78d11d8a37dd7fdaf76fc15c4da&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/roborock-Pro-Ultra-Automatique-Remplissage/dp/B0BSL98D73?&linkCode=ll1&tag=wiseclab0e-21&linkId=c4a6a785c834a94fec7ba9b72d55fb8b&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/roborock-Pro-Ultra-Aspirapolvere-Lavapavimenti/dp/B0BSL98D73?&linkCode=ll1&tag=wiseclab0c-21&linkId=ef767bfeae4513c5831ed68d5d88198a&language=it_IT&ref_=as_li_ss_tl','','B0BVB5PTDK','B0BSL98D73','',NULL,'2AN2O-S81USP01','https://fccid.io/2AN2O-S81USP01',NULL,1,1);
INSERT INTO `robotinfo` VALUES (72,'roborock.vacuum.a51','Roborock S8','Roborock','S80ULT',NULL,'ULTRON-SOUTH','enc, signed, header in TZ',NULL,NULL,NULL,'Allwinner MR813 (4x)',512,'512 MByte (DDR4)',4096,'4GByte eMMC','GD32F303VCT6A','RT8189FS',1,'OpenWRT (custom Tina)','4.9.x',1,2023,NULL,NULL,'y','y (SC035HGS, OV7251, both front-facing) with IR illumination','y (vibrating)','y','y (optional dust collection+)','y','6x','y','Cameras (+illum),Linelaser','y (ultrasonic)','dual rubber','4.3.5','rriot','y','04/2023','y','y',NULL,'medium (partial disassembly)',NULL,'https://builder.dontvacuum.me/_a51.html',NULL,'https://builder.dontvacuum.me/nextgen/','+ (plus) variant has auto empty base station. Base station is voltage dependent. Do not use a US 110V base station in a 220V country. Root was released at DEFCON 31. Root possible without breaking warranty seals.',NULL,NULL,0,1,NULL,'https://www.amazon.com/dp/B0BR5CGYKY?&linkCode=ll1&tag=wiseclab-20&linkId=defed598098a9ed61a05cc96276d31d4&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/roborock-Wischroboter-Absaugstation-Auto-Lifting-Wischsystem-Sprachsteuerung/dp/B0C5FFH7FM?th=1&linkCode=ll1&tag=wiseclab-21&linkId=827a805ea525d2ffacdf238627d55702&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/Roborock-S8-Schwarz-Saug-Wisch-Roboter-Absaugstation/dp/B0BYXM5ZNQ?&linkCode=ll1&tag=wiseclab0e-21&linkId=e030bf49f74268ae7504a81b5b17ee07&language=fr_FR&ref_=as_li_ss_tl','','','B0BR5CGYKY','B0C5FFH7FM','B0BZ3MLRZ9',NULL,'2AN2O-S80ULT01','https://fccid.io/2AN2O-S80ULT01/','CDZ12RR',2,0);
INSERT INTO `robotinfo` VALUES (73,'roborock.vacuum.a46','Roborock G10S','Roborock','','cn','TopazS Plus','enc, signed, header in TZ',NULL,NULL,NULL,'Allwinner MR813 (4x)',1024,'1 GByte (DDR4)',4096,'4GByte eMMC','STM32F103VCT6','RT8189FS',0,'OpenWRT (custom Tina)','4.9.x',2,2022,NULL,NULL,'y','y','y (vibrating)','y','y (included, water change, dust collection)','y','6x','2x','Cameras (+illum),Linelaser','y (ultrasonic)','dual rubber','4.3.5','rriot','y','01/2023','y','y','','medium (partial disassembly)',NULL,'https://builder.dontvacuum.me/_a46.html','roborock.vacuum.a46.jpg','https://builder.dontvacuum.me/nextgen/','Device for the China Mainland market only. Will not work with the Cloud outside of China. Root released at DEFCON 31.',NULL,NULL,0,1,NULL,'',NULL,NULL,NULL,'','','','',NULL,'','',NULL,1,1);
INSERT INTO `robotinfo` VALUES (74,'roborock.vacuum.a65','Roborock S7 Max Ultra','Roborock','',NULL,'','enc(AES-256-CBC), signed (RSA), sqfs',NULL,NULL,NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND',NULL,'Hi3881',0,'Ubuntu 14.04','3.4.x',1,2023,NULL,NULL,'y','n','y','y','y (included, water change, dust collection)','y','6x','2x','IR','y (ultrasonic)','rubber','4.1.8','rriot','y','03/2023','n','y',NULL,'teardown required',NULL,'https://builder.dontvacuum.me/_a65.html','roborock.vacuum.a65.jpg',NULL,NULL,NULL,NULL,0,1,NULL,NULL,'','','','','B0BR5D59MF','B0C2GZQ8LP','B0C2PSBW2V',NULL,'','','',1,1);
INSERT INTO `robotinfo` VALUES (75,'roborock.vacuum.a75','Roborock Q Revo','Roborock',NULL,NULL,'pearl','enc, signed',NULL,NULL,NULL,'Allwinner R16 (4x)',256,'256 MByte',256,'256MByte NAND',NULL,'Hi3881',0,'Ubuntu 14.04','3.4.x',2,2023,NULL,NULL,'y',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'y','Q2/2023','n','y',NULL,'WIP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1,NULL,'https://www.amazon.com/roborock-Revo-Auto-Drying-Self-Refilling-Self-Emptying/dp/B0BVVWN64G?&linkCode=ll1&tag=wiseclab-20&linkId=0d3ab5ee146ec08b34cad31a83eb9d17&language=en_US&ref_=as_li_ss_tl','https://www.amazon.de/roborock-Revo-Doppeldrehmopps-Wasser-Bef%C3%BCllung-Staubbeutel-Entleerung/dp/B0C2YQTHJN?th=1&linkCode=ll1&tag=wiseclab-21&linkId=86916d109b08c7f8d0e5b47bf870153e&language=de_DE&ref_=as_li_ss_tl','https://www.amazon.fr/roborock-Revo-automatiques-Remplissage-Cartographie/dp/B0C2YQTHJN?th=1&linkCode=ll1&tag=wiseclab0e-21&linkId=bc9d9b119dc51fdc8748c5189e2be55f&language=fr_FR&ref_=as_li_ss_tl','https://www.amazon.it/roborock-Aspirapolvere-aspirazione-evitamento-multi-livello/dp/B0C2YQTHJN?th=1&linkCode=ll1&tag=wiseclab0c-21&linkId=248186af50c1024b2bd82bb57f2582b3&language=it_IT&ref_=as_li_ss_tl',NULL,'B0BVVWN64G','B0C2YQTHJN',NULL,NULL,'2AN2O-QX0PEA01','https://fccid.io/2AN2O-QX0PEA01',NULL,1,0);
INSERT INTO `robotinfo` VALUES (76,'ecovacs.5xu9h3','Ecovacs Goat G1','Ecovacs',NULL,NULL,'MR2201','encrypted',NULL,NULL,NULL,'Rockchip RK3588 (8x)',4096,'4 Gbyte (DDR4)',16384,'16Gbyte eMMC',NULL,'RTL8723DS(BT+WiFi)',0,'Linux (+ROS)','5.10.x',2,2023,NULL,NULL,'n','y (SC230AI fisheye, SC301IOT omni)','n','n',NULL,'n','n','n','ToF','n','blades',NULL,'ecovacs','y','Q3/2023','y','n',NULL,'easy (UART)',NULL,NULL,'ecovacs.mr2201.jpg','https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html','Beacons are UWB. DM-verity enabled, do not touch rootfs.','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0);
INSERT INTO `robotinfo` VALUES (77,'ecovacs.lf3bn4','Ecovacs X2 Omni','Ecovacs',NULL,NULL,'ZJ2228','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)',2048,'2 GByte (DDR4)',8192,'8GByte eMMC','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',3,2023,NULL,NULL,'y (180)','y','y (rotating)','y','y (included, water change, dust collection)','y','6x','y','Cameras,Linelaser','y (ultrasonic)','rubber+brush',NULL,'ecovacs','y','Q3/2023','y','n',NULL,'easy (UART)',NULL,NULL,'ecovacs.zj2228.jpg','https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html','Has Microphone. DM-verity enabled, do not touch rootfs! WARNING: The base station is voltage dependant only. Operation of the 110V base station in a region with 220V will make the auto empty fan explode!','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'','','',NULL,'','B0CDPJ2C94','B0CDLW7T16','','y','','','',1,1);
INSERT INTO `robotinfo` VALUES (78,'ecovacs.sdp1y1','Ecovacs Airbot Z1','Ecovacs',NULL,NULL,'AC2109','encrypted',NULL,NULL,NULL,'Horizon X3M (4x)+RV1107',1024,'1 GByte (DDR4)+128MB',512,'512MByte SPI-NAND','GD32F103VCT6','FN-Link 6223a',0,'Linux (+ROS)','4.14.x',4,2022,NULL,NULL,'y','y (2x)','n','n','','y','6x','y','Cameras,Linelaser','n','n',NULL,'ecovacs','y','Q4/2022','y','n',NULL,'easy (UART)',NULL,NULL,'ecovacs.ac2109.jpg','https://dontvacuum.me/talks/37c3-2023/37c3-vacuuming-and-mowing.html','Has Microphone. 2 Robots stacked in one device (bottom: X1 equivalent, top: Rockchip RV1107). Airpurifier','<strong style=\"color: red;\">Do not update firmware via OTA if you plan to ever root your device</strong>',NULL,0,1,NULL,'','','',NULL,'','','B0BBNGWSQZ','','y','','','',0,0);
/*!40000 ALTER TABLE `robotinfo` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

